

patch:
	-@diff -rubB --exclude=.svn --exclude=*.swp XML-TreeBuilder-3.09 XML-TreeBuilder-patched > XML-TreeBuilder-NoExpand.patch

cppatch:
	@cp XML-TreeBuilder-NoExpand.patch ~/Build/rpm/SOURCES/.

