PROD_URL	?= https://www.jboss.com
DOC_URL		?= http://www.redhat.com/docs
STRICT		= 1
LICENSE		= Creative Commons Attribution-NonCommercial-ShareAlike

pre::
	@if [[ "$(PRODUCT)" == "Documentation" ]]; then \
		echo "ERROR! You MUST set a valid PRODUCT to use the JBoss Brand!"; \
		exit 3; \
	fi

